name: Import Code and Set Up Directories

on:
  workflow_dispatch:
    inputs:
      external_repository:
        description: 'https://github.com/WEGULOIMMANUELWANCHA/Holy-Bible-XML-Format'
        required: true

jobs:
  import_and_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Directories
        run: |
          external_repository=${{ github.event.inputs.external_repository }}
          pat=${{ secrets.GIT_PAT }}

          mkdir -p "Holy Books"
          mkdir -p "Holy Books/bibles"

          git config --global user.name "EmmanuelMaisoWancha"
          git config --global user.email "weguloimmanuelwancha@gmail.com"  
          git config --global credential.helper store
          git config --global --add http.extraheader "AUTHORIZATION: bearer $pat"

          git clone --depth 1 $external_repository "Holy Books/bibles"

          git add "Holy Books"
          git commit -m "Import code from $external_repository"
          git push
        working-directory: ${{ github.workspace }}
