name: Build and Deploy Repositories

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bazel
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor -o /usr/share/keyrings/bazel-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update
          sudo apt install -y bazel
          bazel version
        shell: bash
          
      - name: Fetch Repository List
        run: |
          # Fetch the list of repositories to build from a text file (repositories.txt)
          cat GithubRepositories/Repositories/Repositories.txt > repository_list.txt

      - name: Build Binaries 
        run: |
          # Loop through the repository list file and perform actions for each repository
          while IFS= read -r repo; do
            git clone $repo
            repo_name=$(basename $repo .git)
            cd $repo_name

            # Build binaries using Bazel or any other necessary commands
            # ...

            cd ..
            rm -rf $repo_name
          done < repository_list.txt
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./Github\ Pages/Documents/Index.md # Path to publish directory for GitHub Pages

      - name: Store Artifacts as Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Github\ Release/Artifacts/Artifacts@v1.0.0 # Path to artifacts for GitHub Release

